name: GitHub Context Examples

on:
  push

jobs:
  my-context:
    runs-on: ubuntu-20.04
    steps:
      - name: "My Step"
        run: |
          echo "Hello! $MY_ACTION"
          echo "My Actor $MY_ACTOR"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}